-- Phase 29.5 QuickBooks scaffolding closeout (ADR-096).
-- Content-only migration. QuickBooks remains inactive and provider writes remain disabled.
-- Forward-corrects the Phase 19 article rather than editing already-applied V42 history.

update support_article
set title = 'Preparing QuickBooks Online for Rally26',
    summary = 'How owners and administrators prepare Rally26 accounting mappings and understand activation readiness before QuickBooks is enabled.',
    body_markdown = E'## Who manages QuickBooks setup\n\nQuickBooks Online is an organization-owned integration. Organization owners and administrators manage its Rally26 setup. Rally26 Platform Administrators may enter an organization integration workspace only through the normal reasoned, organization-scoped support-access flow; support access never reveals OAuth tokens or provider secrets.\n\n## Current Rally26 status\n\nQuickBooks is **scaffolded but inactive**. Rally26 has contract-tested QuickBooks company, preference, chart-of-accounts, and error shapes; owner-customizable account mapping; export previews; idempotency/error/readback planning; and explicit activation-readiness gates. Phase 29 does not require a live Intuit credential and does not create or change QuickBooks customers, invoices, payments, journal entries, accounts, or other accounting objects.\n\nA saved connection record, realm ID, company name, or local/provider-read result is setup context only. Rally26 does not present those values as live Intuit health.\n\n## Custom chart-of-accounts mapping\n\nRally26 maps accounting **roles** to the QuickBooks accounts your organization already uses. The QuickBooks Account ID is the durable mapping key; account name, fully qualified name, type, and subtype are review snapshots. Rally26 recommends compatible account types, but the owner/accountant makes the final selection. The same QuickBooks account may intentionally serve more than one Rally26 role. Inactive or structurally incompatible accounts are blocked, and unusual but permitted mappings require explicit acknowledgement.\n\nAfter QuickBooks account/company data is refreshed, revalidate the mappings before relying on their readiness result.\n\n## Export preview\n\nExport preview counts eligible Rally26 financial source records and checks the current account mappings. Preview is not an accounting export and never sends financial records to QuickBooks during Phase 29. Rally26 financial and audit history remain authoritative inside Rally26 regardless of future QuickBooks activation.\n\n## What future activation still requires\n\nA separately approved credentialed phase must verify real Intuit credentials and granted scopes, complete sandbox verification, obtain owner/accountant accounting approval, approve a versioned write policy, and explicitly enable provider writes. Until every gate is satisfied, Rally26 remains write-disabled and must not claim QuickBooks is active.',
    category = 'Fees and Payments',
    audience = 'OWNER_ADMIN',
    status = 'PUBLISHED',
    sort_order = 58,
    published_at = coalesce(published_at, now()),
    updated_at = now()
where slug = 'quickbooks-online-readiness';
