spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
          audiences: ${OIDC_AUDIENCE}

leaguelift:
  auth:
    dev-bypass-enabled: false

management:
  endpoint:
    health:
      show-details: never
